# Generated by Django 3.0.8 on 2020-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userImg',
            field=models.ImageField(default='', max_length=200, upload_to='user/profile'),
        ),
    ]
