# Generated by Django 3.0.8 on 2020-08-28 05:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Description', verbose_name='Description')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
            },
        ),
    ]
