export const GET_LEADS = "GET_LEADS";
export const DELETE_LEAD = "DELETE_LEAD";
export const ADD_LEAD = "ADD_LEAD";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const REQUEST_CONFIRMATION = "REQUEST_CONFIRMATION";
export const CANCEL_CONFIRMATION = "CANCEL_CONFIRMATION";
export const CONFIRM = "CONFIRM";